#!/usr/bin/env bun
/**
 * Build the single-executable `opensession` binary with `bun build --compile`.
 *
 * The compiled binary is an ADDITIONAL artefact: `bun run opensession.ts`, the
 * install flow and the tests are untouched. src/main.ts is the front controller
 * (server / CLI / runner-host / mcp-proxy behind one argv), and this script
 * bakes the prebuilt SPA into the binary so it needs no `.frontend-dist`
 * checkout beside it at runtime.
 *
 * Steps:
 *   1. Build the prod frontend into `.frontend-dist` (the same in-process build
 *      the server does at boot) and write the stitched index.html there.
 *   2. Overwrite src/server/embedded-frontend.ts with generated
 *      `import … with { type: "file" }` lines so Bun embeds every built asset.
 *   3. `bun build --compile src/main.ts` with sharp + its native marked
 *      external (a runtime-resolved native can't be embedded).
 *   4. Restore the embedded-frontend.ts stub so the working tree stays clean.
 *
 * Usage: bun scripts/build-compile.ts [--outfile <path>]  (default ./opensession)
 *
 * sharp travels OUTSIDE the binary: the social-card endpoint loads it lazily and
 * degrades to 501 when it (and its @img native) are absent, so the binary boots
 * and serves the UI on its own. To enable social cards, drop a minimal
 * node_modules with `sharp` + `@img/sharp-<platform>` beside the binary (see the
 * README note this script prints at the end).
 */

import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const EMBED_MODULE = join(REPO_ROOT, "src", "server", "embedded-frontend.ts");

function arg(name: string, fallback: string): string {
	const i = process.argv.indexOf(name);
	return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const outfile = resolve(arg("--outfile", join(REPO_ROOT, "opensession")));

// Assets Bun should embed: the hashed SPA bundle + the stable-named wasm, plus
// index.html. Icons/splash/sw.js live under src/frontend and are cosmetic (they
// 404 under the compiled binary; the app still renders) — deliberately not
// embedded to keep the binary lean.
const ASSET_RE = /\.(?:js|css|map|wasm)$/;

async function buildFrontendDist(): Promise<{ version: string; indexHtml: string }> {
	// Imported here (not top-level) so a plain `--help` never pays for the graph.
	const fb = await import("../src/server/frontend-build");
	// Build into a CLEAN dist so only THIS build's hashed assets get embedded.
	// The live server keeps stale chunks around for open tabs (14-day retention);
	// embedding that backlog would bloat the binary by ~90 MB per rebuild.
	rmSync(fb.FRONTEND_DIST, { recursive: true, force: true });
	console.log("[compile] building prod frontend → .frontend-dist …");
	const version = await fb.buildFrontend();
	if (!fb.frontend?.indexHtml) throw new Error("frontend build produced no index.html");
	// buildFrontend keeps the stitched index.html in memory + .bundle-meta.json,
	// not as a dist file. Write it so it can be embedded like any other asset.
	writeFileSync(join(fb.FRONTEND_DIST, "index.html"), fb.frontend.indexHtml);
	return { version, indexHtml: fb.frontend.indexHtml };
}

function generateEmbedModule(distDir: string, version: string): string {
	const names = readdirSync(distDir)
		.filter((n) => !n.startsWith(".") && (n === "index.html" || ASSET_RE.test(n)))
		.sort();
	const lines: string[] = [
		"// AUTO-GENERATED by scripts/build-compile.ts for `bun build --compile`.",
		"// Do not edit or commit: the build restores the src stub afterwards.",
		"/* eslint-disable */",
	];
	const assetEntries: string[] = [];
	let indexIdent = "";
	names.forEach((name, i) => {
		const ident = `__a${i}`;
		lines.push(`import ${ident} from "../../.frontend-dist/${name}" with { type: "file" };`);
		if (name === "index.html") indexIdent = ident;
		else assetEntries.push(`\t\t${JSON.stringify(name)}: ${ident},`);
	});
	if (!indexIdent) throw new Error("index.html missing from .frontend-dist");
	lines.push(
		"",
		"export interface EmbeddedFrontend {",
		"\tversion: string;",
		"\tindexHtmlPath: string;",
		"\tassets: Record<string, string>;",
		"}",
		"",
		"export const EMBEDDED_FRONTEND: EmbeddedFrontend | null = {",
		`\tversion: ${JSON.stringify(version)},`,
		`\tindexHtmlPath: ${indexIdent},`,
		"\tassets: {",
		...assetEntries,
		"\t},",
		"};",
		"",
	);
	return lines.join("\n");
}

async function main(): Promise<void> {
	const stub = await Bun.file(EMBED_MODULE).text();
	const { version } = await buildFrontendDist();
	const distDir = join(REPO_ROOT, ".frontend-dist");
	const generated = generateEmbedModule(distDir, version);

	mkdirSync(dirname(outfile), { recursive: true });
	// `bun build --compile` appends to an existing outfile rather than truncating
	// it, so a rebuild over a prior binary balloons by the embedded-blob size.
	rmSync(outfile, { force: true });
	writeFileSync(EMBED_MODULE, generated);
	try {
		const args = [
			"bun",
			"build",
			"--compile",
			join(REPO_ROOT, "src", "main.ts"),
			"--outfile",
			outfile,
			// sharp's platform native is resolved at runtime and can't be embedded;
			// keep it (and its @img/* backends) out of the trace. The server loads
			// it lazily and degrades without it.
			"--external",
			"sharp",
			"--external",
			"@img/*",
		];
		console.log(`[compile] ${args.join(" ")}`);
		const proc = Bun.spawn(args, { cwd: REPO_ROOT, stdout: "inherit", stderr: "inherit" });
		const code = await proc.exited;
		if (code !== 0) throw new Error(`bun build --compile exited ${code}`);
	} finally {
		writeFileSync(EMBED_MODULE, stub);
	}

	if (!existsSync(outfile)) throw new Error(`expected binary at ${outfile}`);
	const size = (await Bun.file(outfile).arrayBuffer()).byteLength;
	console.log(`\n[compile] built ${outfile} (${(size / 1e6).toFixed(1)} MB, v=${version})`);
	console.log(
		"[compile] sharp is external: PNG social cards need a sibling node_modules " +
			"with `sharp` + `@img/sharp-<platform>`; without it the binary still boots " +
			"and the /session-card endpoint returns 501.",
	);
}

await main();
