import { Marked } from "marked";

// Dedicated marked instance for session messages so this config doesn't leak
// into other markdown (wiki, etc.). Two customisations:
//  - every link opens in a new tab (target=_blank + safe rel)
//  - images/videos render inline, capped in size; clicks open the media
//    lightbox (see MediaLightbox.tsx)
const md = new Marked({ async: false, breaks: true });

function attr(v: string | null | undefined): string {
  return String(v ?? "")
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// Backstage session ids (`bks-<uuidv7>` and legacy `bks-<slug>`), as they appear
// in agent output — usually in a codespan, e.g. a create_session result or an
// orchestrator saying "delegated to `bks-…`". Rendered as a clickable link so you
// can jump from an orchestrator into the worker it spawned (and back). A
// container-level click handler (SessionViewer) navigates on data-session-id,
// since dangerouslySetInnerHTML can't carry React handlers.
const SESSION_ID_EXACT = /^bks-[a-z0-9][a-z0-9-]{5,}$/i;
// Bare (non-code) uuidv7-shaped ids in prose — strict so it can't misfire on
// ordinary text.
const SESSION_ID_BARE =
  /bks-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;

function sessionLink(id: string): string {
  return (
    `<a class="session-link" data-session-id="${attr(id)}" role="button" ` +
    `tabindex="0" title="Open session ${attr(id)}">${attr(id)}</a>`
  );
}

md.use({
  tokenizer: {
    // Strikethrough requires DOUBLE tildes (~~text~~). GFM also accepts a
    // single ~, but session content is full of bare tildes that are NOT
    // strikethrough — ReScript labeled args (`foo(~storyID=…, ~error)`),
    // approximate numbers (`~350 files`), home paths (`~/.config`) — and two of
    // them on a line struck everything between. Returning undefined on a
    // single tilde lets marked fall through to plain text.
    del(this: any, src: string) {
      const m = /^~~(?=\S)([\s\S]*?\S)~~/.exec(src);
      if (!m) return undefined;
      return {
        type: "del",
        raw: m[0],
        text: m[1],
        tokens: this.lexer.inlineTokens(m[1]),
      };
    },
  },
  renderer: {
    // Session content is untrusted (assistant output, tool results, pasted
    // text). marked passes raw HTML through verbatim by default, and we inject
    // the result with dangerouslySetInnerHTML — so an embedded <script> or
    // <img onerror=…> would execute. Escape every raw-HTML token (this method
    // handles both block- and inline-level HTML) so it renders as literal text.
    // All the formatting we actually want (links, images, code) is generated by
    // marked from markdown syntax, not from raw tags, so nothing is lost.
    html(token: any) {
      return attr(token.text ?? token.raw ?? "");
    },
    link(token: any) {
      const text = this.parser.parseInline(token.tokens);
      const title = token.title ? ` title="${attr(token.title)}"` : "";
      return `<a href="${attr(token.href)}"${title} target="_blank" rel="noopener noreferrer">${text}</a>`;
    },
    codespan(token: any) {
      const t = token.text ?? "";
      // A codespan that is exactly a session id becomes a link into that session.
      if (SESSION_ID_EXACT.test(t)) return sessionLink(t);
      return `<code>${attr(t)}</code>`;
    },
    image(token: any) {
      const title = token.title ? ` title="${attr(token.title)}"` : "";
      // Video files pasted with image syntax would render as a broken <img>
      // linking to a new tab — play them inline instead. Clicks on .md-image
      // open the media lightbox (delegated handler in MediaLightbox.tsx); the
      // wrapping <a> stays for cmd/middle-click open-in-tab.
      if (/\.(mp4|webm|mov|m4v)([?#]|$)/i.test(token.href ?? "")) {
        return `<video class="md-video" src="${attr(token.href)}"${title} controls playsinline preload="metadata"></video>`;
      }
      return (
        `<a href="${attr(token.href)}" target="_blank" rel="noopener noreferrer" class="md-image-link">` +
        `<img class="md-image" src="${attr(token.href)}" alt="${attr(token.text)}"${title} loading="lazy" />` +
        `</a>`
      );
    },
  },
  // Bare session ids in prose (not wrapped in backticks) also link. Strict
  // uuidv7 shape so it only fires on real ids.
  extensions: [
    {
      name: "sessionId",
      level: "inline",
      start(src: string) {
        const m = SESSION_ID_BARE.exec(src);
        return m ? m.index : undefined;
      },
      tokenizer(src: string) {
        const m = /^bks-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i.exec(
          src,
        );
        if (m) return { type: "sessionId", raw: m[0], id: m[0] };
      },
      renderer(token: any) {
        return sessionLink(token.id);
      },
    },
  ],
});

/** Render session markdown to HTML (links open in a new tab, images inline). */
export function renderMarkdown(src: string): string {
  try {
    return md.parse(src) as string;
  } catch {
    return src;
  }
}
