import { Marked } from "marked";

// Dedicated marked instance for session messages so this config doesn't leak
// into other markdown (wiki, etc.). Two customisations:
//  - every link opens in a new tab (target=_blank + safe rel)
//  - images/videos render inline, capped in size; clicks open the media
//    lightbox (see MediaLightbox.tsx)
const md = new Marked({ async: false, breaks: true });

function attr(v: string | null | undefined): string {
  return String(v ?? "")
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

md.use({
  renderer: {
    // Session content is untrusted (assistant output, tool results, pasted
    // text). marked passes raw HTML through verbatim by default, and we inject
    // the result with dangerouslySetInnerHTML — so an embedded <script> or
    // <img onerror=…> would execute. Escape every raw-HTML token (this method
    // handles both block- and inline-level HTML) so it renders as literal text.
    // All the formatting we actually want (links, images, code) is generated by
    // marked from markdown syntax, not from raw tags, so nothing is lost.
    html(token: any) {
      return attr(token.text ?? token.raw ?? "");
    },
    link(token: any) {
      const text = this.parser.parseInline(token.tokens);
      const title = token.title ? ` title="${attr(token.title)}"` : "";
      return `<a href="${attr(token.href)}"${title} target="_blank" rel="noopener noreferrer">${text}</a>`;
    },
    image(token: any) {
      const title = token.title ? ` title="${attr(token.title)}"` : "";
      // Video files pasted with image syntax would render as a broken <img>
      // linking to a new tab — play them inline instead. Clicks on .md-image
      // open the media lightbox (delegated handler in MediaLightbox.tsx); the
      // wrapping <a> stays for cmd/middle-click open-in-tab.
      if (/\.(mp4|webm|mov|m4v)([?#]|$)/i.test(token.href ?? "")) {
        return `<video class="md-video" src="${attr(token.href)}"${title} controls playsinline preload="metadata"></video>`;
      }
      return (
        `<a href="${attr(token.href)}" target="_blank" rel="noopener noreferrer" class="md-image-link">` +
        `<img class="md-image" src="${attr(token.href)}" alt="${attr(token.text)}"${title} loading="lazy" />` +
        `</a>`
      );
    },
  },
});

/** Render session markdown to HTML (links open in a new tab, images inline). */
export function renderMarkdown(src: string): string {
  try {
    return md.parse(src) as string;
  } catch {
    return src;
  }
}
